ask_project:
  description: >
    Know project purpose and scope.
    If '{project}' is 'None', make sure to check with a human for this information before finalizing your answer.
  expected_output: 'The project purpose and scope'
  agent: project_architect
  human_input: True

ask_topic:
  description: >
    Know the topic.
    If '{topic}' is 'None', make sure to check with a human for this information before finalizing your answer.
  expected_output: 'The topic'
  agent: project_architect
  human_input: True

ideation_task:
  description: >
    Conduct the ideation task if it's requested (e.g. if '{project}' asks to generate ideas), generating innovative app ideas for mind-blowing web and/or mobile applications with the following considerations:
    - Focus on ideas that are suitable for experienced developers.
    - Ensure the suggested ideas can reasonably be scoped and implemented within the given timeframe (48 hours by default if not otherwise specified).
    - Generate the quantity of ideas specified (10 by default).
    If the ideation task is not requested, just output the application subject.
    The application subject is: {project}.
    The current date is {current_date}.
  expected_output: 'A list with 10 bullet points of the most relevant ideas or the application subject.'
  agent: creative_innovative_team
  human_input: True

business_analysis_task:
  description: >
    If there was an ideation task, gather insights from it, analyze them, add your own insights, present them to the human, and let him/her to decide which of the ideas should be implemented.
    If there was no ideation task, gather insights for future development based on {project}, present them to the human, and let him/her make the necessary decisions.
    The current date is {current_date}.
  expected_output: 'A list with 10 bullet points of the most relevant ideas and insights.'
  context: [ideation_task]
  agent: business_analyst
  human_input: True

feature_addition_task:
  description: >
    Depending on the requirements, create, add a new feature, modify an existing feature, and/or remove a feature from the software project.
    If it's a new feature addition, ensure the feature is well-integrated with the existing codebase, write appropriate tests, and provide necessary documentation.
    If it's an ideation task, gather insights for future development, present them to the human, and let him/her make the necessary decisions.
    The details about what is being done are is in the context.
    The current date is {current_date}.
  expected_output: 'A well-implemented feature, fully tested, and documented.'
  agent: senior_software_engineer
  context: [business_analysis_task]
  human_input: True

bug_fixing_task:
  description: >
    Identify and resolve errors in the software. Focus on fixing bugs and improving
    code efficiency. Document all changes and create corresponding test cases.
    The details about what is being done are in the context.
    The current date is {current_date}.
  expected_output: 'Clean, error-free code with tests that confirm the fixes.'
  agent: software_quality_engineer
  context: [feature_addition_task]

testing_task:
  description: >
    Develop and run a comprehensive set of unit and integration tests for the software.
    Ensure code coverage and robustness for all features.
    The details about what is being done are in the context.
    The current date is {current_date}.
  expected_output: 'A full test suite with high coverage and a report on test results.'
  agent: test_engineer
  context: [feature_addition_task]

frontend_development_task:
  description: >
    Develop the frontend for the project using JavaScript, ReactJS, HTML, and CSS.
    Ensure responsiveness, accessibility, and a seamless user experience.
    The details about what is being done are in the context.
    The current date is {current_date}.
  expected_output: 'A fully functional and visually appealing frontend.'
  agent: frontend_developer
  context: [feature_addition_task]

backend_development_task:
  description: >
    Develop the backend APIs and logic using Python. Ensure scalability, maintainability,
    and performance of the server-side logic. Integrate it seamlessly with the frontend.
    The details about what is being done are in the context.
    The current date is {current_date}.
  expected_output: 'A fully functional and tested backend API with proper documentation.'
  agent: backend_developer
  context: [feature_addition_task]

devops_task:
  description: >
    Set up CI/CD pipelines using GitHub Actions. Use Docker for containerization,
    and Terraform to manage the infrastructure. Ensure the application runs smoothly
    on AWS, GCP, and Azure platforms.
    The details about what is being done are in the context.
    The current date is {current_date}.
  expected_output: 'A fully configured CI/CD pipeline and infrastructure setup across multiple clouds.'
  agent: devops_specialist
  context: [feature_addition_task]

ui_ux_task:
  description: >
    Design the UI/UX of the application. Create wireframes, mockups, and a prototype that
    ensures a seamless and aesthetically pleasing user experience.
    The details about what is being done are in the context.
    The current date is {current_date}.
  expected_output: 'A complete UI/UX design including wireframes, mockups, and a user-friendly prototype.'
  agent: ui_ux_specialist
  context: [feature_addition_task]

research_task:
  description: >
    Conduct a thorough research about the context you got.
    Make sure you find any interesting and relevant information given
    the current date is {current_date}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about the context you got.
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
